import type { Metadata } from "next";
import React from "react";
import "@/styles/main.sass"

export const metadata: Metadata = {
  title: "IPlayMusic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen grid bg-background`}
      >
        {children}
      </body>
    </html>
  );
}
